spring:
  datasource:
    url: jdbc:mysql://localhost:3306/link?useUnicode=true&characterEncoding=UTF-8
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat

  jpa:
    show-sql: true
server:
  port: 8088

mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  type-aliases-package: com.student.demo.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org:
      springframework:
        security:
          - debug
          - info
        web: error
        hibernate:
          SQL: debug
          engine:
            QueryParameters: debug
            query:
              HQLQueryPlan: debug
          type:
            descriptor:
              sql:
                BasicBinder: trace
